-- Run via migrate.js against the schema in HANA_SCHEMA

CREATE TABLE USERS (
  ID           NVARCHAR(36)  PRIMARY KEY,
  NAME         NVARCHAR(255) NOT NULL,
  EMAIL        NVARCHAR(255) NOT NULL UNIQUE,
  PASSWORD_HASH NVARCHAR(255) NOT NULL,
  ROLE         NVARCHAR(20)  DEFAULT 'user',
  CREATED_AT   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TENANTS (
  ID                 NVARCHAR(36)  PRIMARY KEY,
  USER_ID            NVARCHAR(36)  NOT NULL,
  NAME               NVARCHAR(255),
  ENVIRONMENT        NVARCHAR(20)  DEFAULT 'DEV',
  BASE_URL           NVARCHAR(500),
  TOKEN_URL          NVARCHAR(500),
  CLIENT_ID          NVARCHAR(255),
  CLIENT_SECRET_ENC  NVARCHAR(1000),
  STATUS             NVARCHAR(20)  DEFAULT 'UNTESTED',
  LAST_TESTED_AT     TIMESTAMP,
  LAST_ERROR         NVARCHAR(1000),
  IS_ACTIVE          BOOLEAN       DEFAULT FALSE,
  CREATED_AT         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE JIRA_CONFIGS (
  USER_ID        NVARCHAR(36) PRIMARY KEY,
  BASE_URL       NVARCHAR(500),
  EMAIL          NVARCHAR(255),
  API_TOKEN_ENC  NVARCHAR(1000),
  PROJECT_KEY    NVARCHAR(50) DEFAULT 'CPI',
  STATUS         NVARCHAR(20) DEFAULT 'UNTESTED',
  LAST_TESTED_AT TIMESTAMP,
  LAST_ERROR     NVARCHAR(1000),
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE TICKETS (
  ID                 NVARCHAR(36)  PRIMARY KEY,
  USER_ID            NVARCHAR(36)  NOT NULL,
  TICKET_NUMBER      NVARCHAR(50),
  ISSUE_FINGERPRINT  NVARCHAR(255),
  STATUS             NVARCHAR(30)  DEFAULT 'OPEN',
  PRIORITY           NVARCHAR(20),
  CATEGORY           NVARCHAR(50),
  TITLE              NVARCHAR(500),
  DESCRIPTION        NCLOB,
  AI_ANALYZED        BOOLEAN       DEFAULT FALSE,
  PAYLOAD_JSON       NCLOB,       -- catch-all for extra ticket fields
  CREATED_AT         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
CREATE INDEX IDX_TICKETS_USER_FP ON TICKETS (USER_ID, ISSUE_FINGERPRINT);

CREATE TABLE ALERTS (
  ID           NVARCHAR(36) PRIMARY KEY,
  USER_ID      NVARCHAR(36) NOT NULL,
  ACKNOWLEDGED BOOLEAN DEFAULT FALSE,
  PAYLOAD_JSON NCLOB,
  TIMESTAMP    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE MONITORING_LOGS (
  ID           NVARCHAR(36) PRIMARY KEY,
  USER_ID      NVARCHAR(36) NOT NULL,
  PAYLOAD_JSON NCLOB,
  TIMESTAMP    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
CREATE INDEX IDX_MONLOGS_USER_TS ON MONITORING_LOGS (USER_ID, TIMESTAMP);

CREATE TABLE AGENT_LOGS (
  ID           NVARCHAR(36) PRIMARY KEY,
  USER_ID      NVARCHAR(36) NOT NULL,
  PAYLOAD_JSON NCLOB,
  TIMESTAMP    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
CREATE INDEX IDX_AGENTLOGS_USER_TS ON AGENT_LOGS (USER_ID, TIMESTAMP);

ALTER TABLE USERS ADD (ORGANIZATION NVARCHAR(255));